remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

title: Dmitrii Panasenko
description: PhD Student

minimal_mistakes_skin: aqua

author:
  name: "Dmitrii Panasenko"
  # avatar: "/assets/profile.jpg"
  bio: "PhD Student"
  location: "Sweden"
  links:
    - label: "Email"
      url: "mailto:a@a.com"
    - label: "GitHub"
      url: "https://github.com/dmpanasenko"
