remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

title: Dmitrii Panasenko

minimal_mistakes_skin: aqua

atom_feed:
  hide: true

extra_css:
  - /assets/css/custom.css

author:
  avatar: "/assets/profile.jpg"
  bio: "PhD student at Umeå University"
  location: "Umeå, Sweden"
  links:
    - label: "Email (Work)"
      url: "mailto:dmitrii.panasenko@umu.se"
    - label: "Email (Personal)"
      url: "mailto:makare95@mail.ru"
    - label: "ORCID"
      url: "https://orcid.org/0000-0003-4612-6541"
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=v6wsLukAAAAJ"
    - label: "GitHub"
      url: "https://github.com/dmpanasenko"
